### ISSUE TITLE
The Divs in the Middle

### ISSUE THREAD

**Issue by chuckflr** [SolNat99/pet-store#7]
The divs should not have the text centered, only the button on the purchase now for the parrot stuff

**Comment by SolNat99** [comment]
Done with you chuck

**Comment by chuckflr** [comment]
Nah. You always need my help

**Comment by SolNat99** [comment]
Not all the time though. I can figure out stuff sometimes too

**Comment by chuckflr** [comment]
Nah. You always needed help in Chagoyan's class

**Comment by SolNat99** [comment]
Because i was still a scrub then

**Comment by chuckflr** [comment]
And still a scrub to this moment

**Comment by SolNat99** [comment]
Nah brah

**Comment by chuckflr** [comment]
yeah bruh

**Comment by SolNat99** [comment]
Fight me!

**Comment by chuckflr** [comment]
Okay! In Vanguard

**Comment by SolNat99** [comment]
Nah! In Magic!

**Comment by chuckflr** [comment]
How about in both

**Comment by SolNat99** [comment]
I don't know how to fight in Vanguard

**Comment by chuckflr** [comment]
I can show you, I just don't know which deck can beat the other

**Comment by SolNat99** [comment]
You have to beat me in Magic for me to Vanguard

**Comment by chuckflr** [comment]
1 match in Magic and 1 match in Vanguard

**Comment by SolNat99** [comment]
No that isn't fair

**Comment by chuckflr** [comment]
lame

**Comment by SolNat99** [comment]
Fine, fight me in Smash Bros

**Comment by chuckflr** [comment]
shame

**Comment by SolNat99** [comment]
What games to do play?

**Comment by chuckflr** [comment]
Assassin's Creed

**Comment by SolNat99** [comment]
What? Lame

**Comment by chuckflr** [comment]
Nah

**Comment by chuckflr** [comment]
Fight me in yugiman

**Comment by SolNat99** [comment]
You know you can wreck me with your bs decks

**Comment by chuckflr** [comment]
I make a random synchro deck to fight you with

**Comment by SolNat99** [comment]
Lets play uno!

**Comment by chuckflr** [comment]
nah. that game is dumb

**Comment by SolNat99** [comment]
No it's not!

**Comment by chuckflr** [comment]
Let's play dominoes then

**Comment by SolNat99** [comment]
How do you play that?

**Comment by chuckflr** [comment]
bleh XP

**Comment by SolNat99** [comment]
Cruz is weird

**Comment by chuckflr** [comment]
yes he is

**Comment by SolNat99** [comment]
What do we do about him?

**Comment by chuckflr** [comment]
feed him to the wolves

**Comment by SolNat99** [comment]
But they will get sick from eating him

**Comment by chuckflr** [comment]
Okay okay. Cannibals. Knocking out two birds with one stone

**Comment by SolNat99** [comment]
Sounds good to me.

**Comment by chuckflr** [comment]
okay.

**Comment by SolNat99** [comment]
Nah

**Comment by chuckflr** [comment]
why nah

**Comment by SolNat99** [comment]
Because this is better than doing nothing

**Comment by chuckflr** [comment]
but we have like only 8 minutes till we get ready to pack

**Comment by SolNat99** [comment]
Do we really?

**Comment by chuckflr** [comment]
I think so

**Comment by SolNat99** [comment]
You are so nice to Cruz.

**Comment by chuckflr** [comment]
I know that I am :)

**Comment by SolNat99** [comment]
What the heck is going on?

**Comment by chuckflr** [comment]
I do not know

**Comment by SolNat99** [comment]
Should we be concerned?

**Comment by chuckflr** [comment]
just a bit

**Comment by SolNat99** [comment]
I don't know what to do right now

**Comment by chuckflr** [comment]
You could draw on the wall

**Comment by SolNat99** [comment]
But I already did that though

**Comment by chuckflr** [comment]
Then do it again

**Comment by SolNat99** [comment]
I am not that creative

**Comment by chuckflr** [comment]
draw stick figures XD

**Comment by SolNat99** [comment]
Oh, have you seen a youtube video called "Don't Hug Me I'm Scared"?

**Comment by chuckflr** [comment]
not that crazy shenanigan again

**Comment by SolNat99** [comment]
It's interesting to watch, trust me

**Comment by chuckflr** [comment]
nah, I heard that it messes with your mind

**Comment by SolNat99** [comment]
Yea it's fun

**Comment by chuckflr** [comment]
noooooooooo

**Comment by SolNat99** [comment]
Don't be such a baby.

**Comment by chuckflr** [comment]
Nah, I do the mind tricking, not other people

**Comment by SolNat99** [comment]
It's only videos.

**Comment by chuckflr** [comment]
Nah I'm good

**Comment by chuckflr** [comment]
and shouldn't we be packing up now

**Comment by SolNat99** [comment]
yea...

**Comment by chuckflr** [comment]
so what do we do?

**Comment by SolNat99** [comment]
Pack?

**Comment by chuckflr** [comment]
sounds like a good idea
